//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinFleetAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarlinFleetBDEntities : DbContext
    {
        public MarlinFleetBDEntities()
            : base("name=MarlinFleetBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_boat> tbl_boat { get; set; }
        public virtual DbSet<tbl_catch> tbl_catch { get; set; }
        public virtual DbSet<tbl_fishingport> tbl_fishingport { get; set; }
        public virtual DbSet<tbl_fspecies> tbl_fspecies { get; set; }
        public virtual DbSet<tbl_member> tbl_member { get; set; }
        public virtual DbSet<tbl_trip> tbl_trip { get; set; }
    }
}
