//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinFleetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_boat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_boat()
        {
            this.tbl_trip = new HashSet<tbl_trip>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid id_fishingport { get; set; }
        public string name { get; set; }
        public string registration { get; set; }
        public decimal displacement_tons { get; set; }
        public Nullable<decimal> fuel_capacity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string status { get; set; }
    
        public virtual tbl_fishingport tbl_fishingport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trip> tbl_trip { get; set; }
    }
}
