//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinFleetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_trip()
        {
            this.tbl_catch = new HashSet<tbl_catch>();
            this.tbl_member = new HashSet<tbl_member>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid id_boat { get; set; }
        public System.DateTime departure_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string destination { get; set; }
    
        public virtual tbl_boat tbl_boat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_catch> tbl_catch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_member> tbl_member { get; set; }
    }
}
