//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinFleetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_catch
    {
        public System.Guid id { get; set; }
        public System.Guid id_trip { get; set; }
        public System.Guid id_specie { get; set; }
        public int quantity { get; set; }
        public decimal weight { get; set; }
    
        public virtual tbl_fspecies tbl_fspecies { get; set; }
        public virtual tbl_trip tbl_trip { get; set; }
    }
}
