//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinFleetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_member()
        {
            this.tbl_trip = new HashSet<tbl_trip>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string surnames { get; set; }
        public string role { get; set; }
        public Nullable<int> experience_years { get; set; }
        public System.DateTime registration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trip> tbl_trip { get; set; }
    }
}
